create table apartments (
                            id integer generated by default as identity,
                            apartmentNumber integer not null,
                            cleaningDate timestamp,
                            roomAmount integer not null,
                            apartment_id integer,
                            primary key (id)
);
