create table if not exists apartments
(
    id               bigint generated by default as identity,
    apartment_number integer,
    cleaning_date    timestamp,
    room_amount      integer,
    category_id      integer,
    primary key (id)
);

