create table if not exists categories
(
    id            bigint generated by default as identity,
    category_name varchar(255),
    description   varchar(255),
    primary key (id)
);

alter table apartments
    add constraint FK6rnw02aco9vjs982ske31aakv
        foreign key (category_id)
            references categories;
