create table categories (
                            id integer generated by default as identity,
                            categoryName varchar(255),
                            description varchar(255),
                            primary key (id)
);