create table if not exists guests
(
    id              integer generated by default as identity,
    birthday        timestamp,
    check_in_date   timestamp,
    check_out_date  timestamp,
    file_name_photo varchar(255),
    full_name       varchar(255),
    passport        varchar(255),
    guest_id        integer,
    primary key (id)
);
