create table users (
                       id integer generated by default as identity,
                       name varchar(255),
                       role integer,
                       primary key (id)
);

alter table apartments
    add constraint FK83fae4lf85ehdwvvuhq15iio
        foreign key (apartment_id)
            references categories;


alter table guests
    add constraint FK19ymgrma8yweb18c7q614kox9
        foreign key (guest_id)
            references apartments;
