create table if not exists users
(
    id   integer generated by default as identity,
    name varchar(255),
    role integer,
    primary key (id)
);

alter table apartments
    add constraint FK6rnw02aco9vjs982ske31aakv
        foreign key (category_id)
            references categories;


alter table guests
    add constraint FKpljc5pnqdqt5ujk3vduj7gvie
        foreign key (apartment_id)
            references apartments;
